[openweathermap]
enabled = true
api_key = "/home/drat/.config/ntfd/apikey.txt"
# api_key = "env:OWM_API_KEY"                   # Read from an environment variable
# api_key = "--------------------------"
# Find your city at https://openweathermap.org the id will be the last part of the URL
city_id = "7506758"
# How long weather notifications should stay up (in seconds)
notification_timeout = 10
# When notifications are sent, the notification title comes from OpenWeatherMap
# You can customize the message body, or use "" to leave it blank
notification_body = "Expected within the next 3 hours"
# Will default to 10 min for values under 10 min (600 seconds)
sync_frequency = 1800 # 30 minutes
# Output format, using Handlebars syntax, meaning variables should be used like {{ this }}
# Available tokens are:
# - temp_celsius
# - temp_kelvin
# - temp_fahrenheit
# - temp_icon
# - trend
# - forecast_celsius
# - forecast_kelvin
# - forecast_fahrenheit
# - forecast_icon
display = "{{ temp_icon }} {{ temp_fahrenheit }}° {{ trend }} {{ forecast_icon }} {{ forecast_fahrenheit }}°"